PROGRAM signal_test
IMPLICIT NONE
  INTEGER, PARAMETER::SP = SELECTED_INT_KIND(r=8)
  INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(12,100)
  INTEGER(KIND=SP):: n
  REAL(KIND=DP)::inicio,final, TM, c
  REAL(KIND=DP), ALLOCATABLE, DIMENSION(:):: x, y
  REAL(KIND=DP), ALLOCATABLE, DIMENSION(:,:):: A, bt, xt


  USE perceptron_mod_test

END PROGRAM signal_test
