MODULE activation
IMPLICIT NONE
  PUBLIC
  INTEGER, PARAMETER::SP = SELECTED_INT_KIND(r=4)
  INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(8,10)
  REAL(KIND=DP), ALLOCATABLE, DIMENSION(:,:):: xx, w
  REAL(KIND=DP):: x, aa, n, eta

  
CONTAINS

REAL(KIND=DP) FUNCTION bin(x)
INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(8,10) 
REAL(KIND=DP), INTENT(IN):: x

  IF(x >= 0.0 ) THEN
   bin = +1.0   
  ELSE IF (x < 0.0) THEN
   bin = -1.0 
  END IF

END FUNCTION bin

SUBROUTINE treinamento(xx,aa,eta,epoch,w)
!Rotina de treinamento para somente um padrão
IMPLICIT NONE
INTEGER, PARAMETER::SP = SELECTED_INT_KIND(r=4)
INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(8,10)
REAL(KIND=DP), ALLOCATABLE, DIMENSION(:,:), INTENT(IN):: xx
REAL(KIND=DP), ALLOCATABLE, DIMENSION(:,:), INTENT(INOUT):: w
REAL(KIND=DP), INTENT(IN):: aa, eta
INTEGER(KIND=SP), INTENT(IN):: epoch
INTEGER(KIND=SP):: i

DO i=1,epoch
  IF(aa>0) THEN 
    w(i+1,i+1,i+1)=w(i,i,i)
  ELSE IF(aa<=0) THEN
    w(i+1,i+1,i+1)=W(i,i,i)+eta*xx(i,i,i) 
  END IF 
END DO 


END SUBROUTINE treinamento


END MODULE activation
