MODULE activation
IMPLICIT NONE
  PUBLIC
  INTEGER, PARAMETER::SP = SELECTED_INT_KIND(r=4)
  INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(8,10)
  REAL(KIND=DP):: x

  
CONTAINS

REAL(KIND=DP) FUNCTION bin(x)
INTEGER, PARAMETER::DP = SELECTED_REAL_KIND(8,10) 
REAL(KIND=DP), INTENT(IN):: x

  IF(x >= 0.0 ) THEN
   bin = +1.0   
  ELSE IF (x < 0.0) THEN
   bin = -1.0 
  END IF

END FUNCTION bin


END MODULE activation
